-- 临时禁用所有表的RLS，允许匿名用户访问
-- 注意：这仅适用于开发环境，生产环境需要proper认证

-- 禁用projects表的RLS
ALTER TABLE projects DISABLE ROW LEVEL SECURITY;

-- 禁用其他相关表的RLS
ALTER TABLE payment_nodes DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_phases DISABLE ROW LEVEL SECURITY;
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE workers DISABLE ROW LEVEL SECURITY;
ALTER TABLE construction_teams DISABLE ROW LEVEL SECURITY;
ALTER TABLE materials DISABLE ROW LEVEL SECURITY;
ALTER TABLE material_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE financial_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE talents DISABLE ROW LEVEL SECURITY;
ALTER TABLE team_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE worker_assignments DISABLE ROW LEVEL SECURITY;