// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fidhrsooqigtxiidlqeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpZGhyc29vcWlndHhpaWRscWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NzM5NjUsImV4cCI6MjA3MzI0OTk2NX0.RXlQKfcvzfWS-OIzSFJoeSB-_3id-QVE3hsgosGct1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});